### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/rcl#27]
Implement service/client API for rcl.

- C typesupport for services
  - [x] rosidl_generator_c and rosidl_typesupport_introspection_c ros2/rosidl#97
  - [x] rosidl_typesupport_opensplice_c ros2/rmw_opensplice#117
  - [x] rosidl_typesupport_connext_c ros2/rmw_connext#141
- [x] rmw: add service name to client and service structs ros2/rmw#56
- [x] rcl implementation and tests ros2/rcl#30
